### ISSUE TITLE
Add page about mod button features

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/wiki#16]
![image](https://user-images.githubusercontent.com/35232120/97604272-96b0d380-1a0d-11eb-8814-883d30435791.png)
![image](https://user-images.githubusercontent.com/35232120/97604592-f3ac8980-1a0d-11eb-9829-f320791b8987.png)
![image](https://user-images.githubusercontent.com/35232120/97604717-1474df00-1a0e-11eb-9599-ad8d55f88514.png)
![image](https://user-images.githubusercontent.com/35232120/97604778-248cbe80-1a0e-11eb-9909-5157fc224d75.png)
![image](https://user-images.githubusercontent.com/35232120/97604907-4f771280-1a0e-11eb-9627-6492a58650f3.png)
![image](https://user-images.githubusercontent.com/35232120/97604946-5bfb6b00-1a0e-11eb-811a-4c5129fb40b5.png)

Or maybe, that button should just be there per default

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/97697393-ace48f80-1af2-11eb-8487-2f44f7177498.png)
