### ISSUE TITLE
Add information on how to run on macOS to "Troubleshooting" page

### ISSUE THREAD

**Issue by leon-richardt** [Chatterino/wiki#27]
As running the application on mac seems to be non-trivial, it would be helpful to add a section about how to get it to run to the wiki.

![image](https://user-images.githubusercontent.com/35232120/100922295-03702f80-34de-11eb-8dc9-482fb6b17622.png)

**Comment by pajlada** [comment]
should have instructions for how to trust the application since it's not signed
